// examples/with-vue/src/App.vue
<script lang="ts" setup>
import { AuthContextProvider } from "@scute/vue";
import { scute } from "./scute";
import WithScuteUI from "./components/WithScuteUI.vue";
</script>

<template>
  <h1>Vue App</h1>
  <AuthContextProvider :scute-client="scute">
    <WithScuteUI />
  </AuthContextProvider>
</template>

// examples/with-react/src/App.tsx
import { AuthContextProvider } from "@scute/react";
import WithScuteUI from "./components/WithScuteUI";
import { scute } from "./scute";

export default function App() {
  return (
    <AuthContextProvider scuteClient={scute}>
      {/* <WithCustomUI /> */}
      <WithScuteUI />
    </AuthContextProvider>
  );
}
