// examples/with-vue/src/components/Authenticated.vue
<script lang="ts" setup>
import { useAuth } from "@scute/vue";

const { session, user, signOut } = useAuth();
</script>

<template>
  <div style="margin: 1rem">
    {{ session.status }}
    <pre style="font-size: 12px">
       {{ JSON.stringify({ user, session }, null, 4) }}
      </pre
    >
    <button @click="() => signOut()">Sign Out</button>
  </div>
</template>

// apps/dashboard/src/pages/authenticated.tsx
import { useAuth } from "@scute/react";

const AuthenticatedRoute = () => {
  const { session, user, signOut } = useAuth();

  if (session.status === "loading") {
    return null;
  } else if (session.status === "unauthenticated") {
    return "unauthenticated";
  }

  return (
    <div style={{ margin: "1rem" }}>
      <pre style={{ fontSize: "12px" }}>
        {JSON.stringify({ user, session }, null, 4)}
      </pre>
      <button onClick={() => signOut()} style={{ marginTop: "1rem" }}>
        Sign Out
      </button>
    </div>
  );
};

export default AuthenticatedRoute;
