// examples/with-nextjs/src/pages/_app.tsx
import { scuteClient } from "@/scute";
import { AuthContextProvider } from "@scute/react";
import type { AppProps } from "next/app";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <AuthContextProvider scuteClient={scuteClient}>
      <Component {...pageProps} />
    </AuthContextProvider>
  );
}

// examples/with-vue/src/App.vue
<script lang="ts" setup>
import { AuthContextProvider } from "@scute/vue";
import { scute } from "./scute";
import WithScuteUI from "./components/WithScuteUI.vue";
</script>

<template>
  <h1>Vue App</h1>
  <AuthContextProvider :scute-client="scute">
    <WithScuteUI />
  </AuthContextProvider>
</template>
